force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Ticket_Number__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Number__c</fullName>
    <displayFormat>TN-{0000}</displayFormat>
    <label>Ticket Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/TicketRepositoryTest.cls
@IsTest
private class TicketRepositoryTest {
  @TestSetup
  static void setupTestData() {
    List<Flight__c> flights = TestDataFactory.createFlights(100);
    List<Ticket__c> tickets = TestDataFactory.createTickets(1000, flights);
  }

  @IsTest
  static void testGetTicketsByIds() {
    List<Ticket__c> testTickets = [SELECT Id, Name, Ticket_Number__c, Contact__r.Name FROM Ticket__c LIMIT 5];
    Set<Id> ticketIds = new Set<Id>();
    Map<Id, Ticket__c> expectedTickets = new Map<Id, Ticket__c>();

    for (Ticket__c ticket : testTickets) {
      ticketIds.add(ticket.Id);
      expectedTickets.put(ticket.Id, ticket);
    }

    Test.startTest();
    List<Ticket__c> retrievedTickets = TicketRepository.getTicketsByIds(ticketIds);
    Test.stopTest();

    System.assertEquals(testTickets.size(), retrievedTickets.size());

    for (Ticket__c retrievedTicket : retrievedTickets) {
      Ticket__c expectedTicket = expectedTickets.get(retrievedTicket.Id);
      System.assertEquals(expectedTicket.Id, retrievedTicket.Id);
      System.assertEquals(expectedTicket.Name, retrievedTicket.Name);
      System.assertEquals(expectedTicket.Ticket_Number__c, retrievedTicket.Ticket_Number__c);
      System.assertEquals(expectedTicket.Contact__r.Name, retrievedTicket.Contact__r.Name);
    }
  }

  @IsTest
  static void testGetTicketsByFlightId() {
    Flight__c testFlight = [SELECT Id FROM Flight__c LIMIT 1];
    List<Contact> contacts = TestDataFactory.createContacts(10);

    Test.startTest();
    List<Ticket__c> availableTickets = TicketRepository.getTicketsByFlightId(testFlight.Id);
    System.assertEquals(10, availableTickets.size());

    for (Integer i = 0; i < availableTickets.size(); i++) {
      availableTickets[i].Contact__c = contacts[i].Id;
    }
    update availableTickets;

    availableTickets = TicketRepository.getTicketsByFlightId(testFlight.Id);
    System.assertEquals(0, availableTickets.size());
    Test.stopTest();
  }

  // @IsTest
  // static void testGetTicketsByFlightIdAndContactId() {
  //   List<Contact> contacts = TestDataFactory.createContacts(1);
  //   List<Ticket__c> tickets = [SELECT Id, Flight__c FROM Ticket__c LIMIT 1];

  //   List<Ticket__c> ticketsToAssign = new List<Ticket__c>();
  //   for (Ticket__c ticket : tickets) {
  //     ticketsToAssign.add(ticket);
  //   }
  //   List<Flight__c> bookedFlights = TestDataFactory.assignContactsToTickets(ticketsToAssign, contacts);

  //   Test.startTest();
  //   List<Ticket__c> retrievedTickets = TicketRepository.getTicketsByFlightIdAndContactId(bookedFlights[0].Id, contacts[0].Id);
  //   Test.stopTest();

  //   System.assertNotEquals(0, retrievedTickets.size());
  // }

  @IsTest
  static void testUpdateTickets() {
    List<Ticket__c> testTickets = [SELECT Id, Contact__c, Name FROM Ticket__c LIMIT 5];
    Contact newContact = new Contact(FirstName = 'Test', LastName = 'Contact');
    insert newContact;

    for (Ticket__c testTicket : testTickets) {
      testTicket.Contact__c = newContact.Id;
    }

    Test.startTest();
    TicketRepository.updateTickets(testTickets);
    Test.stopTest();

    List<Ticket__c> updatedTickets = [SELECT Id, Contact__c FROM Ticket__c WHERE Id IN :testTickets];
    System.assertEquals(testTickets.size(), updatedTickets.size());

    for (Integer i = 0; i < testTickets.size(); i++) {
      Ticket__c testTicket = testTickets[i];
      Ticket__c updatedTicket = updatedTickets[i];
      System.assertEquals(testTicket.Contact__c, updatedTicket.Contact__c);
    }
  }
}