force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Ticket_Number__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Number__c</fullName>
    <displayFormat>TN-{0000}</displayFormat>
    <label>Ticket Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/TicketRepository.cls
public with sharing class TicketRepository {
  public static Ticket__c getTicketById(Id ticketId) {
    return [SELECT Id, Name, Ticket_Number__c, Contact__r.Name FROM Ticket__c WHERE Id = :ticketId LIMIT 1];
  }

  public static List<Ticket__c> getAvailableTicketsByFlightId(Id flightId) {
    return [SELECT Id, Name, Contact__c, Contact__r.Name FROM Ticket__c WHERE Flight__c = :flightId AND Contact__c = NULL LIMIT 1];
  }

  public static List<Ticket__c> getTicketsByFlightIdAndContactId(Id flightId, Id contactId) {
    return [SELECT Id, Name, Ticket_Number__c, Contact__c FROM Ticket__c WHERE Flight__c = :flightId AND Contact__c = :contactId LIMIT 1];
  }

  public static void updateTicket(Ticket__c tiket) {
    try {
      update tiket;
    } catch (Exception e) {
      throw new AuraHandledException('Error occurred while updating tickets: ' + e.getMessage());
    }
  }
}