force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>Start</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <label>Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Preferred_Trip_Start__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Trip_Start__c</fullName>
    <label>Preferred Trip Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flight search</fullName>
                <default>true</default>
                <label>Flight search</label>
            </value>
            <value>
                <fullName>Flight booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@IsTest
public with sharing class TestDataFactory {
  public static List<Contact> createContacts(Integer recordCount) {
    List<Contact> contacts = new List<Contact>();
    for (Integer i = 0; i < recordCount; i++) {
      contacts.add(new Contact(FirstName = 'Test', LastName = 'Contact ' + i));
    }
    insert contacts;
    return contacts;
  }

  public static List<Flight__c> createFlights(Integer recordCount) {
    List<Flight__c> flights = new List<Flight__c>();
    for (Integer i = 0; i < recordCount; i++) {
      flights.add(new Flight__c(Name = 'FL' + i, Start__c = DateTime.now().addDays(i)));
    }
    insert flights;
    return flights;
  }

  public static List<Ticket__c> createTickets(Integer recordCount, List<Flight__c> flights) {
    List<Ticket__c> tickets = new List<Ticket__c>();
    Integer flightsCount = flights.size();
    Integer ticketsPerFlight = recordCount / flightsCount;

    for (Integer i = 0; i < flightsCount; i++) {
      Flight__c flight = flights[i];
      for (Integer j = 0; j < ticketsPerFlight; j++) {
        tickets.add(new Ticket__c(Name = 'TKT' + (i * ticketsPerFlight + j), Flight__c = flight.Id));
      }
    }
    insert tickets;
    return tickets;
  }

  public static List<Trip__c> createTrips(Integer recordCount, List<Contact> contacts) {
    List<Trip__c> trips = new List<Trip__c>();
    for (Integer i = 0; i < recordCount; i++) {
      trips.add(new Trip__c(Contact__c = contacts[i].Id, Preferred_Trip_Start__c = Date.today().addDays(i)));
    }
    insert trips;
    return trips;
  }

  public static List<Flight__c> assignContactsToTickets(List<Ticket__c> tickets, List<Contact> contacts) {
    Set<Id> flightIds = new Set<Id>();

    for (Integer i = 0; i < tickets.size(); i++) {
      if (i < contacts.size()) {
        tickets[i].Contact__c = contacts[i].Id;
        flightIds.add(tickets[i].Flight__c);
      }
    }
    update tickets;
    return [SELECT Id FROM Flight__c WHERE Id IN :flightIds];
  }

  public static List<Trip__c> assignFlightsToTrips(List<Flight__c> flights, List<Trip__c> trips) {
    List<Trip__c> tripsToUpdate = new List<Trip__c>();

    for (Integer i = 0; i < trips.size(); i++) {
      if (i < flights.size()) {
        Trip__c trip = trips[i];
        trip.Flight__c = flights[i].Id;
        trip.Status__c = 'Flight booked';
        tripsToUpdate.add(trip);
      }
    }
    update tripsToUpdate;
    return [SELECT Id FROM Trip__c WHERE Id IN :tripsToUpdate];
  }
}