force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Ticket_Number__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Number__c</fullName>
    <displayFormat>TN-{0000}</displayFormat>
    <label>Ticket Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/TicketCalloutServiceTest.cls
@IsTest
public with sharing class TicketCalloutServiceTest {
  @TestSetup
  static void setupTestData() {
    List<Contact> contacts = TestDataFactory.createContacts(1);
    List<Flight__c> flights = TestDataFactory.createFlights(1);
    List<Ticket__c> tickets = TestDataFactory.createTickets(1, flights);
  }

  @IsTest
  static void testSendMessageToExternalAPI() {
    Test.setMock(HttpCalloutMock.class, new HttpCalloutMockTest());

    List<Ticket__c> tickets = [SELECT Id, Name, Ticket_Number__c, Contact__r.Name FROM Ticket__c LIMIT 1];
    Set<Id> ticketIds = new Set<Id>{ tickets[0].Id };

    Test.startTest();
    TicketCalloutService.sendMessageToExternalAPI(ticketIds);
    Test.stopTest();
  }
}