force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <displayFormat>FN-{0000}</displayFormat>
    <label>Flight Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>Start</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <label>Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flight search</fullName>
                <default>true</default>
                <label>Flight search</label>
            </value>
            <value>
                <fullName>Flight booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FlightRepositoryTest.cls
@IsTest
private class FlightRepositoryTest {
  //   @TestSetup
  //   static void setupTestData() {
  //     TestDataFactory.createTestData(1000);
  //   }

  //   @IsTest
  //   static void testGetFlightsByDateAndKeyword() {
  //     Date preferredDate = Date.today();
  //     String keyword = 'FL';

  //     Test.startTest();
  //     List<Flight__c> flights = FlightRepository.getFlightsByDateAndKeyword(preferredDate, keyword);
  //     Test.stopTest();

  //     System.assertEquals(1000, flights.size(), 'Incorrect number of flights returned.');

  //     for (Flight__c flight : flights) {
  //       // Perform assertions on each flight record as needed
  //       System.assertEquals('FL', flight.Flight_Number__c.substring(0, 2), 'Incorrect flight number format.');
  //       System.assertEquals(preferredDate, flight.Start__c.date(), 'Incorrect flight start date.');
  //     }
  //   }

  //   @IsTest
  //   static void testGetFlightById() {
  //     List<Flight__c> flights = [SELECT Id FROM Flight__c LIMIT 1];
  //     System.assertNotEquals(0, flights.size(), 'No flights found for testing.');

  //     Test.startTest();
  //     Flight__c flight = FlightRepository.getFlightById(flights[0].Id);
  //     Test.stopTest();

  //     System.assertNotEquals(null, flight, 'Flight record not retrieved.');
  //     System.assertEquals(flights[0].Id, flight.Id, 'Incorrect flight record retrieved.');
  //   }

  //   @IsTest
  //   static void testBookFlightForTrip() {
  //     List<Trip__c> trips = [SELECT Id, Contact__c, Status__c FROM Trip__c LIMIT 1];
  //     List<Flight__c> flights = [SELECT Id FROM Flight__c WHERE Id NOT IN (SELECT Flight__c FROM Ticket__c WHERE Contact__c != NULL) LIMIT 1];

  //     System.assertNotEquals(0, trips.size(), 'No trips found for testing.');
  //     System.assertNotEquals(0, flights.size(), 'No available flights found for testing.');

  //     Trip__c trip = trips[0];
  //     Flight__c flight = flights[0];

  //     Test.startTest();
  //     Ticket__c bookedTicket = FlightRepository.bookFlightForTrip(trip.Id, flight.Id);
  //     Test.stopTest();

  //     System.assertNotEquals(null, bookedTicket, 'Ticket not booked.');
  //     System.assertEquals(trip.Contact__c, bookedTicket.Contact__c, 'Incorrect contact on booked ticket.');
  //     System.assertEquals('Flight booked', trip.Status__c, 'Trip status not updated to "Flight booked".');
  //     System.assertEquals(flight.Id, trip.Flight__c, 'Incorrect flight on trip.');

  //     // Ensure the booked ticket is no longer available
  //     List<Ticket__c> availableTickets = [SELECT Id FROM Ticket__c WHERE Flight__c = :flight.Id AND Contact__c = NULL];
  //     System.assertEquals(0, availableTickets.size(), 'Available ticket still found after booking.');
  //   }

  //   // @IsTest
  //   // static void testGetFlightDetailsByTripId() {
  //   //   List<Trip__c> trips = [SELECT Id, Contact__c, Flight__c FROM Trip__c LIMIT 1];
  //   //   System.assertNotEquals(0, trips.size(), 'No trips found for testing.');

  //   //   Trip__c trip = trips[0];

  //   //   Test.startTest();
  //   //   FlightRepository.FlightDetailsWrapper flightDetails = FlightRepository.getFlightDetailsByTripId(trip.Id);
  //   //   Test.stopTest();

  //   //   if (trip.Flight__c != null) {
  //   //     Flight__c flight = [SELECT Flight_Number__c, Start__c FROM Flight__c WHERE Id = :trip.Flight__c LIMIT 1];

  //   //     if (flight != null) {
  //   //       System.assertEquals(flight.Flight_Number__c, flightDetails.flightNumber, 'Incorrect flight number.');
  //   //       System.assertEquals(String.valueOf(flight.Start__c), flightDetails.flightStart, 'Incorrect flight start date.');
  //   //     }
  //   //   }
  //   // }
  // }
}