force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <displayFormat>FN-{0000}</displayFormat>
    <label>Flight Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>Start</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Ticket_Number__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Number__c</fullName>
    <displayFormat>TN-{0000}</displayFormat>
    <label>Ticket Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <label>Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flight search</fullName>
                <default>true</default>
                <label>Flight search</label>
            </value>
            <value>
                <fullName>Flight booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FlightControllerTest.cls
@IsTest
private class FlightControllerTest {
  @TestSetup
  static void setupTestData() {
    List<Contact> contacts = TestDataFactory.createContacts(1);
    List<Flight__c> flights = TestDataFactory.createFlights(1);
    List<Trip__c> trips = TestDataFactory.createTrips(1, contacts);
    List<Ticket__c> tickets = TestDataFactory.createTickets(10, flights);
    TestDataFactory.assignFlightsToTrips(flights, trips);
    TestDataFactory.assignContactsToTickets(tickets, contacts);
  }

  @IsTest
  static void testGetAvailableFlightsWithKeyword() {
    List<Flight__c> freeFlights = TestDataFactory.createFlights(1);
    List<Ticket__c> freeTickets = TestDataFactory.createTickets(1, freeFlights);
    String keyword = 'FL';
    Date preferredDate = Date.today();
    Trip__c trip = [SELECT Id FROM Trip__c LIMIT 1];

    Test.startTest();
    List<Flight__c> availableFlights = FlightController.getAvailableFlightsWithKeyword(trip.Id, keyword);
    Test.stopTest();

    System.assertNotEquals(0, availableFlights.size());
    for (Flight__c flight : availableFlights) {
      System.assert(flight.Name.contains(keyword));
      System.assertEquals(preferredDate, flight.Start__c.date());
    }
  }

  @IsTest
  static void testBookFlight_Success() {
    Test.setMock(HttpCalloutMock.class, new HttpCalloutMockTest());
    List<Flight__c> freeFlights = TestDataFactory.createFlights(1);
    List<Contact> newContacts = TestDataFactory.createContacts(1);
    Ticket__c freeTickets = TestDataFactory.createTickets(1, freeFlights)[0];
    Trip__c newTrip = TestDataFactory.createTrips(1, newContacts)[0];

    Test.startTest();
    FlightController.bookFlight(newTrip.Id, freeFlights[0].Id);
    Test.stopTest();

    Trip__c updatedTrip = [SELECT Id, Flight__c, Status__c FROM Trip__c WHERE Id = :newTrip.Id];
    System.assertEquals(freeFlights[0].Id, updatedTrip.Flight__c);
    System.assertEquals('Flight booked', updatedTrip.Status__c);
  }

  @IsTest
  static void testCancelBookingFlight() {
    Trip__c trip = [SELECT Id FROM Trip__c LIMIT 1];
    trip.Flight__c = TestDataFactory.createFlights(1)[0].Id;
    trip.Status__c = 'Flight booked';
    update trip;

    Test.startTest();
    FlightController.cancelBookingFlight(trip.Id);
    Test.stopTest();

    Trip__c updatedTrip = [SELECT Id, Flight__c, Status__c FROM Trip__c WHERE Id = :trip.Id];
    System.assertEquals(null, updatedTrip.Flight__c);
    System.assertEquals('Flight search', updatedTrip.Status__c);
  }

  @IsTest
  static void testGetFlightDetails() {
    Trip__c trip = [SELECT Id, Flight__c, Contact__c FROM Trip__c LIMIT 1];
    Flight__c flight = [SELECT Id, Flight_Number__c, Start__c FROM Flight__c WHERE Id = :trip.Flight__c LIMIT 1];
    Ticket__c ticket = [SELECT Id, Name, Ticket_Number__c FROM Ticket__c WHERE Flight__c = :flight.Id AND Contact__c = :trip.Contact__c LIMIT 1];

    Test.startTest();
    FlightDetailsWrapper result = FlightController.getFlightDetails(trip.Id);
    Test.stopTest();

    System.assertEquals(flight.Flight_Number__c, result.flightNumber);
    System.assertEquals(String.valueOf(flight.Start__c), result.flightStart);
    System.assertEquals(ticket.Name, result.ticketName);
    System.assertEquals(ticket.Ticket_Number__c, result.ticketNumber);
  }
}