force-app/main/default/objects/Confirmation_ticket_setting__c/Confirmation_ticket_setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Confirmation ticket setting</label>
</CustomObject>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Ticket_Number__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Number__c</fullName>
    <displayFormat>TN-{0000}</displayFormat>
    <label>Ticket Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/TicketCalloutService.cls
public with sharing class TicketCalloutService {
  @future(callout=true)
  public static void sendMessageToExternalAPI(Set<Id> ticketIds) {
    List<Ticket__c> tickets = TicketRepository.getTicketsByIds(ticketIds);

    if (tickets != null) {
      Confirmation_ticket_setting__c customSetting = Confirmation_ticket_setting__c.getInstance();

      String endpointUrl;
      if (customSetting != null && !String.isBlank(customSetting.URL__c)) {
        endpointUrl = customSetting.URL__c;
      } else {
        endpointUrl = 'https://private-1ce70-testassign.apiary-mock.com ' + '/ticket';
      }

      for (Ticket__c ticket : tickets) {
        Map<String, Object> requestBodyMap = new Map<String, Object>();
        requestBodyMap.put('ticketnumber', ticket.Ticket_Number__c);
        requestBodyMap.put('contact', ticket.Contact__r.Name);
        String requestBody = JSON.serialize(requestBodyMap);
        HttpResponse response = CalloutService.makePostCallout(endpointUrl, requestBody);

        if (response.getStatusCode() == 201) {
          System.debug('Callout successful. Response: ' + response.getBody());
        } else {
          System.debug('Callout failed with error. Status code: ' + response.getStatusCode() + ', Body: ' + response.getBody());
        }
      }
    }
  }
}