force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <label>Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flight search</fullName>
                <default>true</default>
                <label>Flight search</label>
            </value>
            <value>
                <fullName>Flight booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TripControllerTest.cls
@IsTest
private class TripControllerTest {
  @TestSetup
  static void setupTestData() {
    List<Contact> contacts = TestDataFactory.createContacts(1);
    List<Trip__c> trips = TestDataFactory.createTrips(1, contacts);
  }

  @IsTest
  static void testIsTripBookedFlight_FlightBooked() {
    Trip__c trip = [SELECT Id, Status__c FROM Trip__c LIMIT 1];
    trip.Status__c = 'Flight booked';
    update trip;

    Test.startTest();
    Boolean isBooked = TripController.isTripBookedFlight(trip.Id);
    Test.stopTest();

    System.assertEquals(true, isBooked);
  }

  @IsTest
  static void testIsTripBookedFlight_FlightSearch() {
    Trip__c trip = [SELECT Id, Status__c FROM Trip__c LIMIT 1];
    trip.Status__c = 'Flight search';
    update trip;

    Test.startTest();
    Boolean isBooked = TripController.isTripBookedFlight(trip.Id);
    Test.stopTest();

    System.assertEquals(false, isBooked);
  }

  //   @IsTest
  //   static void testIsTripBookedFlight_InvalidStatus() {
  //     Trip__c trip = [SELECT Id, Status__c FROM Trip__c LIMIT 1];
  //     trip.Status__c = 'Invalid status';
  //     update trip;

  //     Test.startTest();
  //     try {
  //       Boolean isBooked = TripController.isTripBookedFlight(trip.Id);
  //       System.assert(false, 'Exception should have been thrown');
  //     } catch (AuraHandledException e) {
  //       System.assertEquals('Invalid trip status.', e.getMessage());
  //     }
  //     Test.stopTest();
  //   }

  //   @IsTest
  //   static void testIsTripBookedFlight_TripNotFound() {
  //     Test.startTest();
  //     try {
  //       Boolean isBooked = TripController.isTripBookedFlight('invalidTripId');
  //       System.assert(false, 'Exception should have been thrown');
  //     } catch (AuraHandledException e) {
  //       System.assertEquals('Trip not found.', e.getMessage());
  //     }
  //     Test.stopTest();
  //   }
}